version: '3'
services:
   postgresql:
      container_name: db-siscor
      image: postgres:9.6
      restart: always

      ports:
       - "5433:5432"

      environment:
       - POSTGRES_DATABASE=siscor
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=4321x2
      
      volumes:
       - ./sql:/sql
       - postgres-data:/usr/lib/postgresql/data

   web:
      container_name: web-siscor
      image: yousan/php5.6-apache:latest
      restart: always
      ports:
        - 8080:80

      volumes:
       - ./app:/app
       - ./vhost.conf:/etc/apache2/sites-available/000-default.conf

      links:
       - postgresql

volumes:
      postgres-data:
 